/**
 * @file Constants for Select Text Item
 * @author Regu & Rajaguru
 */


const SELECT_TEXT_TYPES ="SELECT_TEXT_TYPES";
const MANUALLY_SELECTED_RESPONSE ="MANUAL_SELECTIONS";
const WHOLE_PARAGRAPHS ="PARAGRAPHS";
const WHOLE_WORDS ="WORDS";
const WHOLE_SENTENCES ="SENTENCES";
const CLASS ="class";
const SELECT_TEXT_TAG ="selecttext";
const SELECTED_RESPONSE_CLASS ="st-selected-response";
const CORRECT_RESPONSE_AREA ="correctResponseArea";
const DATA_ITEMKEY = "code";
const ST_BORDER_RESPONSE = 'ST_BORDER_RESPONSE';
const ST_BORDER_HIGHLIGHT = "ST_BORDER_HIGHLIGHT";
const ST_BR_NONE = "ST_BR_NONE";
const ST_BLACK = "#000000";
const ST_RED = "#FF0000";
const ST_YELLOW = "#FFFF00";


export {
  SELECT_TEXT_TYPES,
  MANUALLY_SELECTED_RESPONSE,
  WHOLE_PARAGRAPHS,
  WHOLE_WORDS,
  WHOLE_SENTENCES,
  CLASS,
  SELECT_TEXT_TAG,
  SELECTED_RESPONSE_CLASS,
  CORRECT_RESPONSE_AREA,
  DATA_ITEMKEY,
  ST_BORDER_RESPONSE,
  ST_BORDER_HIGHLIGHT,
  ST_BR_NONE,
  ST_BLACK,
  ST_RED,
  ST_YELLOW
}